# Wine Dataset

<br/>

Esses dados são resultados de uma análise química de vinhos cultivados em uma região da Itália, derivados de três cultivares diferentes.

Objetivo do estudo, é realizar previsão se o vinho é tinto ou branco.

In [ ]:
# Importanto as bibliotecas

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
# Carregando o dataset

arquivo = pd.read_csv('wine_dataset.csv')

In [23]:
# Visualizar o tamanho do dataset

arquivo.shape

(6497, 13)

In [6]:
# Visualizar as primeiras linhas

arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [7]:
# Visualizar as últimas linhas 
    
arquivo.tail()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [8]:
# Trocando os valores da variável target style, para númerico

arquivo['style'] = arquivo['style'].replace('red', 0)
arquivo['style'] = arquivo['style'].replace('white', 1)

In [10]:
# Visualizar as primeiras linhas após a substituição dos valores da variável númerica

arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [11]:
# Visualizar as últimas linhas após a substituição dos valores da variável númerica

arquivo.tail()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [15]:
# Separando as variáveis preditoras que ficaram armazenadas na nova variável x

x = arquivo.drop('style', axis = 1)

In [16]:
# Separando as variável alvo que ficara armazenada em y

y = arquivo['style']

In [18]:
# conjunto de dados para treino e teste. Será utilizado 30% dos dados para teste e 70% para treino

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [24]:
# Modelo utilizado para o algoritmo para criar as árvores de decisão

modelo = ExtraTreesClassifier()
modelo.fit(x_treino, y_treino)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [43]:
# Imprimindo o resultado

resultado = modelo.score(x_teste, y_teste)
print("Acurácia de:", resultado * 100)

Acurácia de: 99.6923076923077

In [48]:
# filtrando 5 amostras aleatórias de x

x_teste[205:210]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2451,6.9,0.18,0.36,1.3,0.036,40.0,117.0,0.99340,3.27,0.95,9.5,7
5899,6.4,0.29,0.30,6.5,0.209,62.0,156.0,0.99478,3.10,0.40,9.4,5
5783,6.4,0.33,0.28,4.0,0.040,24.0,81.0,0.99030,3.26,0.64,12.6,7
745,7.3,0.51,0.18,2.1,0.070,12.0,28.0,0.99768,3.52,0.73,9.5,6
4006,7.6,0.31,0.27,5.8,0.036,23.0,109.0,0.99399,3.34,0.54,11.0,6

In [49]:
# filtrando 5 amostras aleatórias de y

y_teste[205:210]

2451    1
5899    1
5783    1
745     0
4006    1
Name: style, dtype: int64

In [50]:
# Realizando as previsões para verificar se o modelo acertou

previsoes = modelo.predict(x_teste[205:210])
previsoes

array([1, 1, 1, 0, 1], dtype=int64)